# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: detect-aws-credentials
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Run Python linter
#        args: [--max-line-length=103]
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.22.1
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible
  - repo: local
    hooks:
      - id: run-tests
        name: Run all tests
        entry: >
          bash -c 'cd provisioning &&
          docker run
          --rm
          -v ./app:/home/cdktf/app
          -v ~/.ssh/id_rsa.pub:/home/cdktf/.ssh/id_rsa.pub:ro
          -v ~/.aws:/home/cdktf/.aws:ro
          cdktf:local all-tests'
        language: system
        pass_filenames: false
