---
- name: Check if swap is enabled
  ansible.builtin.command: swapon --show
  register: swap_check
  ignore_errors: true
  changed_when: false

- name: Ensure swap is not enabled
  ansible.builtin.fail:
    msg: "Swap is enabled on the system"
  when: swap_check.stdout != ""

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ worker_node_hostname }}"
  become: true

- name: Update /etc/hosts with the new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^127.0.0.1'
    line: "127.0.0.1 {{ ansible_hostname }} localhost {{ ansible_hostname }}.kubernetes.local"
  become: true

- name: Create K8S API server DNS alias
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ k8s_control_plane_ip }} server.kubernetes.local"
  become: true
