---
- name: Install kube-apiserver binary
  block:
    - name: Capture kube-apiserver installed version
      ansible.builtin.command: "{{ kube_apiserver_target_path }}/kube-apiserver --version"
      register: kube_apiserver_installed
      ignore_errors: true
      changed_when: false

    - name: Set kube-apiserver installed version fact
      ansible.builtin.set_fact:
        kube_apiserver_installed_version: "{{ kube_apiserver_installed.stdout_lines[0].split(' ')[1] }}"
      when: kube_apiserver_installed.rc == 0

    - name: Stop and remove existing kube-apiserver if version mismatch
      when: kube_apiserver_installed.rc == 0 and kube_apiserver_installed_version != kube_apiserver_version
      block:
        - name: Ensure kube-apiserver is stopped
          ansible.builtin.systemd_service:
            name: kube-apiserver
            state: stopped
          become: true

        - name: Remove kube-apiserver target directory
          ansible.builtin.file:
            path: "{{ kube_apiserver_target_path }}"
            state: absent

    - name: Install kube-apiserver binary if not installed or version mismatch
      when: kube_apiserver_installed_version|default('') != kube_apiserver_version
      block:
        - name: Download kube-apiserver binary
          ansible.builtin.get_url:
            url: "{{ kube_apiserver_url }}/{{ kube_apiserver_version }}/bin/{{ ansible_system | lower }}/{{ architecture }}/kube-apiserver"
            dest: "{{ kube_apiserver_target_path }}"
            owner: root
            group: root
            mode: "0755"
          become: true

- name: Setup PKI
  block:
    - name: Ensure PKI directory exists
      ansible.builtin.file:
        path: "{{ kube_apiserver_pki_path }}"
        state: directory
        mode: "0700"
      become: true

    - name: Copy certs and keys to target directory
      ansible.builtin.copy:
        src: "{{ kube_apiserver_pki_src_path }}/{{ item }}"
        dest: "{{ kube_apiserver_pki_path }}"
        remote_src: false
        owner: root
        group: root
        mode: "0600"
      loop:
        - "{{ kube_apiserver_service_account_key_file }}"
        - "{{ kube_apiserver_service_account_signing_key_file }}"
        - "{{ kube_apiserver_client_ca_file }}"
        - "{{ kube_apiserver_tls_cert_file }}"
        - "{{ kube_apiserver_tls_private_key_file }}"
      become: true
      notify: Restart kube-apiserver service

- name: Install and configure kube-apiserver service
  block:
    - name: Ensure service env directory exists
      ansible.builtin.file:
        path: "{{ kube_apiserver_service_env_path }}"
        state: directory
        mode: "0755"
      become: true

    - name: Create service environment file
      ansible.builtin.template:
        src: kube-apiserver.env.j2
        dest: "{{ kube_apiserver_service_env_path }}/kube-apiserver"
        mode: "0644"
      become: true
      notify: Restart kube-apiserver service

    - name: Create systemd service file
      ansible.builtin.template:
        src: kube-apiserver.service.j2
        dest: /lib/systemd/system/kube-apiserver.service
        mode: "0644"
      become: true
      notify: Restart kube-apiserver service

- name: Trigger handler immediately after service configuration
  ansible.builtin.meta: flush_handlers

- name: Wait for kube-apiserver port to become available
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    timeout: 30
