---
- name: Bootstrap K8S control plane
  hosts: k8s_control_plane
  gather_facts: true
  vars:
    service_account_private_key_file: "service-accounts.key"
    etcd_port: 2379
    # Do not change service_cluster_ip_range after the cluster has already been brought up once
    # https://github.com/k3s-io/k3s/issues/3489
    k8s_service_cluster_ip_range: "10.32.0.0/24"
  vars_files:
    - vars/common_vars.yaml

  pre_tasks:
    - name: Include K8S binaries URL setup task
      ansible.builtin.include_tasks: tasks/set_k8s_binaries_url.yaml

  roles:
    # TODO delete
    - role: display_time
    - role: journald
    - role: control_plane_system_configuration
    - role: etcd
      vars:
        etcd_client_port: "{{ etcd_port }}"
    - role: kube_apiserver
      vars:
        kube_apiserver_version: "{{ k8s_version }}"
        kube_apiserver_etcd_port: "{{ etcd_port }}"
        kube_apiserver_pki_src_path: "{{ k8s_pki_path }}"
        kube_apiserver_service_account_key_file: "service-accounts.crt"
        kube_apiserver_service_account_signing_key_file: "{{ service_account_private_key_file }}"
        kube_apiserver_client_ca_file: "{{ ca_file }}"
        kube_apiserver_tls_cert_file: "kube-api-server.crt"
        kube_apiserver_tls_private_key_file: "kube-api-server.key"
        kube_apiserver_service_cluster_ip_range: "{{ k8s_service_cluster_ip_range }}"
    - role: kubectl
      vars:
        kubectl_version: "{{ k8s_version }}"
    - role: kubectl_config_admin
      vars:
        kubectl_config_admin_pki_src_path: "{{ k8s_pki_path }}"
        kubectl_config_admin_ca_file: "{{ ca_file }}"
        kubectl_config_admin_admin_tls_cert_file: "admin.crt"
        kubectl_config_admin_admin_tls_private_key_file: "admin.key"
    - role: kube_controller_manager
      vars:
        kube_controller_manager_version: "{{ k8s_version }}"
        kube_controller_manager_pki_src_path: "{{ k8s_pki_path }}"
        kube_controller_manager_client_ca_file: "{{ ca_file }}"
        kube_controller_manager_root_ca_file: "{{ ca_file }}"
        kube_controller_manager_tls_cert_file: "kube-controller-manager.crt"
        kube_controller_manager_tls_private_key_file: "kube-controller-manager.key"
        kube_controller_manager_cluster_signing_cert_file: "{{ ca_file }}"
        kube_controller_manager_cluster_signing_key_file: "ca.key"
        kube_controller_manager_service_account_private_key_file: "{{ service_account_private_key_file }}"
        kube_controller_manager_service_cluster_ip_range: "{{ k8s_service_cluster_ip_range }}"
    - role: kube_scheduler
      vars:
        kube_scheduler_version: "{{ k8s_version }}"
        kube_scheduler_pki_src_path: "{{ k8s_pki_path }}"
        kube_scheduler_client_ca_file: "{{ ca_file }}"
        kube_scheduler_tls_cert_file: "kube-scheduler.crt"
        kube_scheduler_tls_private_key_file: "kube-scheduler.key"
