---
- name: Bootstrap K8S worker node
  hosts: k8s_worker_node
  gather_facts: true
  vars_files:
    - vars/common_vars.yaml

  pre_tasks:
    - name: Include K8S binaries URL setup task
      ansible.builtin.include_tasks: tasks/set_k8s_binaries_url.yaml

    - name: Set control plane private IP
      ansible.builtin.set_fact:
        k8s_control_plane_ip: "{{ hostvars[groups['k8s_control_plane'][0]]['private_ip_address'] }}"

    - name: Set worker node hostname
      ansible.builtin.set_fact:
        worker_node_hostname: "node-0"

  roles:
    - role: journald
    - role: worker_node_system_configuration
    - role: containerd
    - role: kubectl
      vars:
        kubectl_version: "{{ k8s_version }}"
    - role: kubelet
      vars:
        kubelet_version: "{{ k8s_version }}"
        kubelet_pki_src_path: "{{ k8s_pki_path }}"
        kubelet_client_ca_file: "{{ ca_file }}"
        kubelet_tls_cert_file: "{{ kubelet_client_certificate_file }}"
        kubelet_tls_private_key_file: "{{ kubelet_client_key_file }}"
    - role: kube_proxy
      vars:
        kube_proxy_version: "{{ k8s_version }}"
        kube_proxy_pki_src_path: "{{ k8s_pki_path }}"
        kube_proxy_client_ca_file: "{{ ca_file }}"
        kube_proxy_tls_cert_file: "kube-proxy.crt"
        kube_proxy_tls_private_key_file: "kube-proxy.key"
    - role: check_node_status
