---
# - name: Set up PKI prereq
#   hosts: localhost
#   tasks:
#     - name: Generate service account keys
#       ansible.builtin.command: openssl genrsa -out "/home/ansible/.k8s/{{ item }}" 2048
#       args:
#         creates: "/home/ansible/.k8s/{{ item }}"
#       loop:
#         - service_account.key
#         - service_account_signing.key

# TODO
# Pass service-account-key-file, service-account-signing-key-file and set service-account-issuer
- name: Bootstrap K8S control plane
  hosts: k8s_control_plane
  #  gather_facts: true
  vars:
  #    service_account_keys_src_path: /home/ansible/.k8s
  #    service_account_key_name: service_account.key
  #    service_account_signing_key_name: service_account_signing.key
    etcd_port: 2379

  tasks:
    - name: Determine host architecture
      ansible.builtin.set_fact:
        architecture: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

  roles:
    - role: display_time
    - role: journald
    - role: etcd
      vars:
        etcd_client_port: "{{ etcd_port }}"
    # - role: kube_apiserver
    #   vars:
    #     kube_apiserver_etcd_port: "{{ etcd_port }}"
    #    - role: control_plane
    #      vars:
    #        control_plane_service_account_keys_src_path: "{{ service_account_keys_src_path }}"
    #        control_plane_service_account_key_name: "{{ service_account_key_name }}"
    #        control_plane_service_account_signing_key_name: "{{ service_account_signing_key_name }}"
    #        control_plane_etcd_port: "{{ etcd_port }}"
