---
kube_apiserver_url: "https://dl.k8s.io"
kube_apiserver_version: "v1.31.1"
kube_apiserver_target_path: "/usr/local/bin"
kube_apiserver_service_cluster_ip_range: "10.43.0.0/16"
kube_apiserver_service_env_path: "/etc/default"
