---
kube_apiserver_target_path: "/usr/local/bin"
kube_apiserver_pki_path: "/var/lib/kubernetes"
kube_apiserver_service_env_path: "/etc/default"

# ***
# kube-apiserver options
# ***
kube_apiserver_service_account_issuer: "https://kubernetes.default.svc"
kube_apiserver_auth_modes: "Node,RBAC"
kube_apiserver_audit_log:
  maxage: 30
  maxbackup: 3
  maxsize: 100
kube_apiserver_audit_log_path: "/var/log/k8s_audit.log"
kube_apiserver_bind_address: "0.0.0.0"
# If not set, default to the internal IP address of the node
# kube_apiserver_external_hostname: X.X.X.X
