---
- name: Create DNS K8S server aliases
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }} server server.kubernetes.local"
  become: true

# Add a static route to worker node for pods CIDR
- name: Disable cloud-init network configuration
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      network: {config: disabled}
    mode: "0644"
  become: true

- name: Create new Netplan configuration file
  ansible.builtin.copy:
    dest: /etc/netplan/01-netcfg.yaml
    content: |
      network:
        version: 2
        ethernets:
          {{ ansible_facts.default_ipv4.interface }}:
            match:
              macaddress: {{ ansible_facts.default_ipv4.macaddress }}
            dhcp4: true
            dhcp6: false
            set-name: {{ ansible_facts.default_ipv4.interface }}
            routes:
              - to: {{ pods_cidr_range }}
                via: {{ k8s_worker_node_ip }}
    mode: "0600"
  become: true

- name: Apply Netplan configuration
  ansible.builtin.command: "netplan apply"
  changed_when: false # not clean
  become: true
