# Makefile
.PHONY: plan deploy destroy

PROVISIONING_SCRIPT = ./provisioning.sh

plan:
	@bash $(PROVISIONING_SCRIPT) plan 

deploy:
	@bash $(PROVISIONING_SCRIPT) deploy 

destroy:
	@bash $(PROVISIONING_SCRIPT) destroy 

